### ISSUE TITLE
请问这个报错怎么解决？

### ISSUE THREAD

**Issue by HuangYuChuh** [smthemex/ComfyUI_Stable_Makeup#13]
OSError: Error no file named model_index.json found in directory /hy-tmp/huggingfacedownload/hub/models--lllyasviel--control_v11p_sd15_canny/snapshots/115a470d547982438f70198e353a921996e2e819.

**Comment by smthemex** [comment]
奇怪，怎么会有canny模型，你这个是外网网络不通的缘故。或者之前没有配置过controlnet canny，你试试全局外网，或者镜像站，然后我检查一下代码。

**Comment by smthemex** [comment]
我检查了下代码，发现方法的模型应该是controlnet 融合模型，出现这种情况可能是你模型没有下齐的缘故，按说明把文件都下载到指定目录试试。

**Comment by HuangYuChuh** [comment]
好的，很感谢解答！
