### ISSUE TITLE
【Error】Invalid `original_config_file` provided. Please set it to a valid file path or URL.

### ISSUE THREAD

**Issue by thinkingjimmy** [smthemex/ComfyUI_Stable_Makeup#14]
新版本去掉了 runwayml/stable-diffusion-v1-5 的 repo 输入框，但应该仍然需要下载 “runwayml/stable-diffusion-v1-5”的配套config文件？那应该下载到哪个文件夹呢？

**Comment by smthemex** [comment]
自动下载到C盘，开全局下载一次，后面就没有了。

**Comment by smthemex** [comment]
不对，你的是本地文件缺失，你的model/configs/v1-inference.yaml 文件怎么没有？这个是comfyUI自带的啊

**Comment by thinkingjimmy** [comment]
哦哦 应该是我挂载 image volume 的问题，感谢。
