### ISSUE TITLE
openai/clip-vit-large-patch14 要放哪，里面有啥文件呀  

### ISSUE THREAD

**Issue by liushh39** [smthemex/ComfyUI_Stable_Makeup#15]

**Comment by smthemex** [comment]
直接让系统下载就好，没多大的文件，你要自己下，随便放那里，模型和config文件都配套好就行，路径填绝对路径，用/而不是用\

**Comment by liushh39** [comment]
是下这个吗？https://huggingface.co/openai/clip-vit-large-patch14/tree/main

里面没有pytorch_model_1.bin呀

**Comment by smthemex** [comment]
![image](https://github.com/user-attachments/assets/7d0f3552-d81d-45d2-a2fe-d669564b67e4)
这些是文件名，都要有，我这是link，你按名称一一下载就好，没有bin文件

**Comment by liushh39** [comment]
我都下了
<img width="952" alt="image" src="https://github.com/user-attachments/assets/a2858366-f504-45bd-a24d-de40e9f8ed43">

**Comment by smthemex** [comment]
地址错误，你得使用 X:/XXXX/XXX/clip-vit-large-patch14 这样的类型

**Comment by liushh39** [comment]
/root/paddlejob/workspace/env_run/output/ComfyUI/models/clip_vision/openai/clip-vit-large-patch14
还是一样的错误。。

**Comment by xiezhen223600** [comment]
配置文件应该放在什么地方？clip-vit-large-patch14在哪里下载？

**Comment by smthemex** [comment]
上面的回复里 地址和名称都有了，你看下字。
