### ISSUE TITLE
Although I have git this plugin, why does my import fail? Is there a specific operation procedure? How to use no need requirements.txt?

### ISSUE THREAD

**Issue by sundaxiong6** [smthemex/ComfyUI_Stable_Makeup#18]
![微信截图_20240808224729](https://github.com/user-attachments/assets/d55b6159-bf12-4485-b738-c364d8224914)

**Comment by smthemex** [comment]
You can try checking the console to see what libraries are missing, or you can open 'no need requirements. txt' to view the corresponding library requirements and install the missing libraries. The reason why I didn't use requirements. txt is that if you install it directly, your ComfyUI probably won't work.
你可以试着查看控制台，看缺少什么库，也可以打开no need requirements.txt，查看对应的库需求，安装缺少的库。我没有使用 requirements.txt的原因是：如果你直接安装，你的comfyUI多半用不了。
