### ISSUE TITLE
哪位可爱的大佬帮忙看下这个问题是啥原因啊

### ISSUE THREAD

**Issue by cj920815** [smthemex/ComfyUI_Stable_Makeup#19]
![image](https://github.com/user-attachments/assets/543a078a-6d2c-4329-83ce-1250805735fe)
![Uploading 问题.png…]()

**Comment by cj920815** [comment]
预览图像是黑的，没有输出

**Comment by smthemex** [comment]
换个底模试试

**Comment by cj920815** [comment]
哇！大佬回复我这个小菜鸟了！


我晚上回去换个底膜试试，不用v1-5-pruned-emaonly.safetensor这个了







发自我的iPhone


------------------ 原始邮件 ------------------
发件人: smthemex ***@***.***&gt;
发送时间: 2024年8月26日 08:30
收件人: smthemex/ComfyUI_Stable_Makeup ***@***.***&gt;
抄送: cj920815 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [smthemex/ComfyUI_Stable_Makeup] 哪位可爱的大佬帮忙看下这个问题是啥原因啊 (Issue #19)





 
换个底模试试

**Comment by cj920815** [comment]
> 换个底模试试

大佬，我回去重新装了一遍，应该是我之前环境的问题导致的，1.5的底模能跑，没啥问题。

我试了下效果，还有很大的提升空间啊。

希望越做越好
