### ISSUE TITLE
401 Client Error. (Request ID: Root=1-66d47630-3d6b302552eec4be3b6d71ca;9ad558fb-3d69-408c-bbef-e9fcb383077f) Repository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main.

### ISSUE THREAD

**Issue by SmartRick** [smthemex/ComfyUI_Stable_Makeup#20]
![image](https://github.com/user-attachments/assets/a6dbf5f2-0e26-4fac-83db-4ba6e4297902)

401 Client Error. (Request ID: Root=1-66d47630-3d6b302552eec4be3b6d71ca;9ad558fb-3d69-408c-bbef-e9fcb383077f) Repository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main. Please make sure you specified the correct `repo_id` and `repo_type`. If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password.

求助，sd1.5模型被官方删除了，找不到仓库了，怎么办呢？

**Comment by smthemex** [comment]
我看看能不能集成进去吧，这个也是意想不到的删库跑路。

**Comment by smthemex** [comment]
此问题已解决，请按使用更新后的插件。
