### ISSUE TITLE
报错，求助

### ISSUE THREAD

**Issue by T8mars** [smthemex/ComfyUI_Stable_Makeup#23]
![image](https://github.com/user-attachments/assets/c0b2e169-4df3-49f0-9304-8798236d9803)
![image](https://github.com/user-attachments/assets/951f0bf6-2b26-4e9d-93b1-c55e83499c59)
我设置的路径：D:/ComfyUI-aki-v1.3/models/openai/clip-vit-large-patch
![image](https://github.com/user-attachments/assets/cd37dccb-83cb-4abf-836b-22be1719033e)
我以前能用的，还做过这个帖子，但是一段时间没用今天就报错了，麻烦看看要怎么解决

**Comment by smthemex** [comment]
> StableMakeup_LoadModel CLIPVisionModel does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention yet. Please request the support for this architecture: [huggingface/transformers#28005](https://github.com/huggingface/transformers/issues/28005). If you believe this error is a bug, please open an issue in Transformers GitHub repository and load your model with the argument `attn_implementation="eager"` meanwhile. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="eager")`

这个问题是新版diffusers出来的，按理我已经修改了，加入了 attn_implementation="eager"，你更新过最新的插件没

**Comment by T8mars** [comment]
嗯刚更新完修好了， 谢谢大佬，感恩，我想问下，这个只能做正方形图片吗，因为，我改长方形尺寸他哪怕是64的倍数一直提示我必须是64的倍数

**Comment by T8mars** [comment]
![image](https://github.com/user-attachments/assets/c995ea7c-3940-4c4c-8a14-0519387a51f6)
![image](https://github.com/user-attachments/assets/9e5f195e-3c37-4752-8b09-7e9683908467)

**Comment by T8mars** [comment]
![image](https://github.com/user-attachments/assets/31fd9200-a1c4-4ec4-8309-a1357ca03949)
没事，加了个剪裁恢复搞好了，谢谢大佬，没其他问题了感谢

**Comment by T8mars** [comment]
其他没问题了，大佬有什么QQ群微信群之类的吗

**Comment by smthemex** [comment]
我B站上有发过群号，不过群里不热闹，不加也罢

**Comment by T8mars** [comment]
大佬B站来一个我去关注一波

**Comment by smthemex** [comment]
B站找我这个号去掉ex

**Comment by T8mars** [comment]
谢谢，发现之前关注过了，已三连，感谢大佬
