### ISSUE TITLE
(IMPORT FAILED)

### ISSUE THREAD

**Issue by StrikerMax** [smthemex/ComfyUI_Stable_Makeup#24]
Could not load.
The ComfyUI custom nodes manager say: (IMPORT FAILED).  
Trying the "try fix" button, nothing change.
Required models are putted in: ...\ComfyUI_windows_portable\ComfyUI\models\stable_makeup
(in readme you wrote table_makeup) XD

Questions that I encountered:

..where to put the clip model? in which format? in my case: 
...\ComfyUI_windows_portable\ComfyUI\models\clip\clip-vit-large-patch14.safetensors       CORRECT?

and..following the link to download "mobilenet0.25_Final.pth" it download a file called 
"densnet121.pth"  it's the same? i have to rename it or what?

**Comment by smthemex** [comment]
“Openai/clip vit-large-patch14” is automatically downloaded and is usually located in the "user/youname/. cache/huggingface/hub" directory. It is not a standalone model and comes with a matching config file。
openai/clip-vit-large-patch14 是自动下载的，一般在“user/youname/.cache/huggingface/hub”目录下，不是单体的模型，会有配套的config文件

**Comment by StrikerMax** [comment]
Checked, is there. "user/myname/. cache/huggingface/hub"

and about the mobilenet question? "The link to download "mobilenet0.25_Final.pth" it download a file called
"densnet121.pth" it's the same? i have to rename it or what?"

**Comment by smthemex** [comment]
yes, rename it

**Comment by StrikerMax** [comment]
Models putted in :
F:\SD\ComfyUI_windows_portable\ComfyUI\models\stable_makeup
![files](https://github.com/user-attachments/assets/48947a2a-41e4-4e9c-a383-6021a4aad5f2)

this is what about requirements:

F:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup>pip install -r requirements.txt
Requirement already satisfied: insightface in c:\users\maxbe\miniconda3\lib\site-packages (from -r requirements.txt (line 1)) (0.7.3)
Requirement already satisfied: numpy in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: onnx in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (1.16.2)
Requirement already satisfied: tqdm in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (4.66.4)
Requirement already satisfied: requests in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: matplotlib in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (3.9.2)
Requirement already satisfied: Pillow in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (10.4.0)
Requirement already satisfied: scipy in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (1.14.1)
Requirement already satisfied: scikit-learn in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (1.5.2)
Requirement already satisfied: scikit-image in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (0.24.0)
Requirement already satisfied: easydict in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (1.13)
Requirement already satisfied: cython in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (3.0.11)
Requirement already satisfied: albumentations in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (1.4.15)
Requirement already satisfied: prettytable in c:\users\maxbe\miniconda3\lib\site-packages (from insightface->-r requirements.txt (line 1)) (3.11.0)
Requirement already satisfied: PyYAML in c:\users\maxbe\miniconda3\lib\site-packages (from albumentations->insightface->-r requirements.txt (line 1)) (6.0.2)
Requirement already satisfied: pydantic>=2.7.0 in c:\users\maxbe\miniconda3\lib\site-packages (from albumentations->insightface->-r requirements.txt (line 1)) (2.9.2)
Requirement already satisfied: albucore>=0.0.15 in c:\users\maxbe\miniconda3\lib\site-packages (from albumentations->insightface->-r requirements.txt (line 1)) (0.0.17)
Requirement already satisfied: eval-type-backport in c:\users\maxbe\miniconda3\lib\site-packages (from albumentations->insightface->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: opencv-python-headless>=4.9.0.80 in c:\users\maxbe\miniconda3\lib\site-packages (from albumentations->insightface->-r requirements.txt (line 1)) (4.10.0.84)
Requirement already satisfied: networkx>=2.8 in c:\users\maxbe\miniconda3\lib\site-packages (from scikit-image->insightface->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: imageio>=2.33 in c:\users\maxbe\miniconda3\lib\site-packages (from scikit-image->insightface->-r requirements.txt (line 1)) (2.35.1)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\maxbe\miniconda3\lib\site-packages (from scikit-image->insightface->-r requirements.txt (line 1)) (2024.9.20)
Requirement already satisfied: packaging>=21 in c:\users\maxbe\miniconda3\lib\site-packages (from scikit-image->insightface->-r requirements.txt (line 1)) (24.1)
Requirement already satisfied: lazy-loader>=0.4 in c:\users\maxbe\miniconda3\lib\site-packages (from scikit-image->insightface->-r requirements.txt (line 1)) (0.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\maxbe\miniconda3\lib\site-packages (from matplotlib->insightface->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\maxbe\miniconda3\lib\site-packages (from matplotlib->insightface->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\maxbe\miniconda3\lib\site-packages (from matplotlib->insightface->-r requirements.txt (line 1)) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\maxbe\miniconda3\lib\site-packages (from matplotlib->insightface->-r requirements.txt (line 1)) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\maxbe\miniconda3\lib\site-packages (from matplotlib->insightface->-r requirements.txt (line 1)) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\maxbe\miniconda3\lib\site-packages (from matplotlib->insightface->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\maxbe\miniconda3\lib\site-packages (from onnx->insightface->-r requirements.txt (line 1)) (5.28.2)
Requirement already satisfied: wcwidth in c:\users\maxbe\miniconda3\lib\site-packages (from prettytable->insightface->-r requirements.txt (line 1)) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\maxbe\miniconda3\lib\site-packages (from requests->insightface->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\maxbe\miniconda3\lib\site-packages (from requests->insightface->-r requirements.txt (line 1)) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\maxbe\miniconda3\lib\site-packages (from requests->insightface->-r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\maxbe\miniconda3\lib\site-packages (from requests->insightface->-r requirements.txt (line 1)) (2024.7.4)
Requirement already satisfied: joblib>=1.2.0 in c:\users\maxbe\miniconda3\lib\site-packages (from scikit-learn->insightface->-r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\maxbe\miniconda3\lib\site-packages (from scikit-learn->insightface->-r requirements.txt (line 1)) (3.5.0)
Requirement already satisfied: colorama in c:\users\maxbe\miniconda3\lib\site-packages (from tqdm->insightface->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\maxbe\miniconda3\lib\site-packages (from pydantic>=2.7.0->albumentations->insightface->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in c:\users\maxbe\miniconda3\lib\site-packages (from pydantic>=2.7.0->albumentations->insightface->-r requirements.txt (line 1)) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\maxbe\miniconda3\lib\site-packages (from pydantic>=2.7.0->albumentations->insightface->-r requirements.txt (line 1)) (4.12.2)
Requirement already satisfied: six>=1.5 in c:\users\maxbe\miniconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface->-r requirements.txt (line 1)) (1.16.0)

F:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup>


But still:
![fault](https://github.com/user-attachments/assets/72ef1708-43b2-4c31-afe2-011e4bf0d2bf)

Faulty..

**Comment by StrikerMax** [comment]
Total VRAM 24576 MB, total RAM 32689 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\SD\ComfyUI_windows_portable\ComfyUI\web
F:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.51)
### ComfyUI Revision: 2710 [38c69080] | Released on '2024-09-20'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
F:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2024-09-21 12:17:36.811065: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-21 12:17:37.585824: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "F:\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup\__init__.py", line 2, in <module>
    from .stable_makeup_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup\stable_makeup_nodes.py", line 11, in <module>
    from diffusers import (DDIMScheduler, ControlNetModel,
ImportError: cannot import name 'LCMScheduler' from 'diffusers' (F:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)

Cannot import F:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Stable_Makeup module for custom nodes: cannot import name 'LCMScheduler' from 'diffusers' (F:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)

**Comment by StrikerMax** [comment]
maybe diffusers are deprecated..

**Comment by StrikerMax** [comment]
For everyone involving in the same problem:

SOLVED:
Need to update diffusers version. 
Runned this in ComfyUI_windows_portable folder:

python_embeded\python.exe -m pip install -U diffusers

**Comment by StrikerMax** [comment]
Tnx for your attention, and for your precious job @smthemex
