### ISSUE TITLE
original_config_file cannot be find

### ISSUE THREAD

**Issue by alboto** [smthemex/ComfyUI_Stable_Makeup#26]
`
original_config_file=os.path.join(folder_paths.models_dir,"configs","v1-inference.yaml")
`
Where to find this file?

**Comment by smthemex** [comment]
Origin ComfyUI  contain this file，looks like your comfyUI is Modified version。
you can downlaod this file from [ComfyUI ](https://github.com/comfyanonymous/ComfyUI/tree/master/models/configs)
and put it into “comfyUI/models/configs” folder.
