### ISSUE TITLE
我已经将openai/clip-vit-large-patch14下载到服务器ComfyUI/models/clip中，但是当运行的时候，仍然会从huggingface.co或hrhuggingface.co中获取clip-vit-large-patch14，因为网络问题，最终导致失败，请问该如何处理，感谢

### ISSUE THREAD

**Issue by natie20210522** [smthemex/ComfyUI_Stable_Makeup#27]
我已经将openai/clip-vit-large-patch14下载到服务器ComfyUI/models/clip中，但是当运行的时候，仍然会从huggingface.co或hrhuggingface.co中获取clip-vit-large-patch14，因为网络问题，最终导致失败，请问该如何处理，感谢

**Comment by natie20210522** [comment]
![1731738172919](https://github.com/user-attachments/assets/79009058-478b-40f6-87ee-7421ca073183)
非常感谢您的回复，但是我从自己的云端，还是有报错，但是我在kaggle就可以跑的通，不知道什么问题，感谢

**Comment by natie20210522** [comment]
![1731738600720](https://github.com/user-attachments/assets/e8604428-bb55-49bf-aa51-d6880bc505c3)
这是kaggle的表现

**Comment by smthemex** [comment]
还是路径的问题，地址栏就没有正确指向本地clip模型路径，所以自动下载，而如果梯子卡了下载不了，就会报错

**Comment by yiyabo** [comment]
有没有人尝试在代码中直接修改加载地址呢？让代码去某一个地址加载模型，而不是去huggingface下载，或者去检测缓存。

**Comment by smthemex** [comment]
你填写的地址就是自定义啊， 如果是openai/clip-vit-large-patch14就检查缓存或者自动下载，如果是X:/XXX/XX/clip-vit-large-patch14 就加载这个路径的模型，这么简单了还要啥？

**Comment by yiyabo** [comment]
刚刚看了下，修改了一下模型的导入。我这边情况有点特殊，不大方便直接进行地址更改😂。
        from transformers import CLIPTextModel, CLIPTokenizer

        # 加载本地的 text_encoder 和 tokenizer 模型
        text_encoder = CLIPTextModel.from_pretrained("/xxxxxxx/openai/clip-vit-large-patch14")
        tokenizer = CLIPTokenizer.from_pretrained("/xxxxxxx/openai/clip-vit-large-patch14")

        # 使用 from_single_file 加载 StableDiffusionPipeline，并手动指定 text_encoder 和 tokenizer
        pipe = StableDiffusionPipeline.from_single_file(
            ckpt_path,
            original_config=original_config_file,
            text_encoder=text_encoder,
            tokenizer=tokenizer
        )

**Comment by yiyabo** [comment]
> ```
>     刚刚看了下，修改了一下模型的导入。我这边情况有点特殊，不大方便直接进行地址更改😂。
>     from transformers import CLIPTextModel, CLIPTokenizer
> 
>     # 加载本地的 text_encoder 和 tokenizer 模型
>     text_encoder = CLIPTextModel.from_pretrained("/xxxxxxx/openai/clip-vit-large-patch14")
>     tokenizer = CLIPTokenizer.from_pretrained("/xxxxxxx/openai/clip-vit-large-patch14")
> 
>     # 使用 from_single_file 加载 StableDiffusionPipeline，并手动指定 text_encoder 和 tokenizer
>     pipe = StableDiffusionPipeline.from_single_file(
>         ckpt_path,
>         original_config=original_config_file,
>         text_encoder=text_encoder,
>         tokenizer=tokenizer
>     )
> ```

补充一下，还需要指定一下clip
        clip = "/root/models/openai/clip-vit-large-patch14"
        makeup_encoder = detail_encoder(Unet, clip, "cuda", dtype=torch.float32)

**Comment by smthemex** [comment]
你直接在repo填写"/root/models/openai/clip-vit-large-patch14" 不行吗?

**Comment by yiyabo** [comment]
> 你直接在repo填写"/root/models/openai/clip-vit-large-patch14" 不行吗?

就是因为不行😂，所以才需要从代码层次进行更改

**Comment by natie20210522** [comment]
哈哈，有这么多回复了啊，其实我也知道改地址，但是我把能放的文件夹都放了clip-vit-large-patch14，包括models，clip，节点文件夹也放了，然后在工作流里把地址改了个遍，也没成功，看来还是技术不过关，插件没问题，表现很好，我测试了比cosxl表现要好，暂时先不弄了，如果有需要就去kaggle生成一下就行了，感谢回复

**Comment by SaintSelena** [comment]
我这边遇到了相似的问题，但我发现我把clip路径填写正确还是有报错，后面仔细看了下，还有一个文件包缺了：stable-diffusion-safety-checker，在抱脸下载内容后放在\ComfyUI-aki-v1.3\.cache\sdwebuilauncher\hfmirror\refs\CompVis\stable-diffusion-safety-checker\main，重启后解决。但这个故事还没有结束，接着我就爆显存了……6个g的显存我只能走到这里了……你们加油
