### ISSUE TITLE
routing problem 

### ISSUE THREAD

**Issue by 807502278** [smthemex/ComfyUI_Stable_Makeup#6]
I downloaded all the models, but when it ran, it still automatically downloaded this model from (https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development)

Can “ComfyUI\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\32bd64288804d66eefd0ccbe215aa642df71cc41\model.safetensors” be moved to “ComfyUI\models\stable_makeup” ?

**Comment by 807502278** [comment]
噢噢，下载的是不是这个？那没事了
![image](https://github.com/user-attachments/assets/80944966-20ce-4df6-ae79-51eba7b5b782)

**Comment by 807502278** [comment]
不过建议sd1.5，unet，vae用内置的节点加载

**Comment by smthemex** [comment]
原方法不好调用comfyUI的加载方法，包括unet加载器,因为还要内部调用vae 和clip,而且原方法是魔改过pipe的，暂时没法直接用。

**Comment by 807502278** [comment]
那可以增加下拉框来选择comfyui\models里的unet，vae，原版sd1.5，clip吗？

**Comment by smthemex** [comment]
那不是多此一举了嘛，还多了3个菜单，你就把SD1.5的融合到一个包里最省事，或者直接下载到C盘，也就3个多G，以后都必要选什么。这个方法改了controlnet，clip的一些细节，comfyui的也不好融入，比较麻烦。
