### ISSUE TITLE
1 error

### ISSUE THREAD

**Issue by T8mars** [smthemex/ComfyUI_Stable_Makeup#7]
![image](https://github.com/user-attachments/assets/f3b7ff3c-347f-40ea-98dc-62ee103a7b4e)
![image](https://github.com/user-attachments/assets/04a1153c-3fff-4251-8f02-6d770086fdd1)
please help

**Comment by smthemex** [comment]
Your workflow is outdated, please update to the latest version. The new version has removed the ckpts option. You can open a new workflow in the example

**Comment by T8star1984** [comment]
![125dd64a00f6ba1e0e8036c992f7fbf2](https://github.com/user-attachments/assets/ee57f8ac-d09d-4275-a446-ec90b681160d)
![037e5b8067300c75f281995dd1cc809a](https://github.com/user-attachments/assets/13250967-f113-4ae4-91e8-1f2019f4600f)
![9cc8989b30d21a8f3679f3e091d56c07](https://github.com/user-attachments/assets/1da9e6dd-4a3a-44a1-8a75-0c286a6b1c88)

it is the lastest version,,...I have reinstalled it

**Comment by T8star1984** [comment]
![c8a401d4baf0b7544ad9bd14ca42714a](https://github.com/user-attachments/assets/5502f241-9cdd-42d2-9bd8-03e91f7b03b7)
![20c17d7c68b1527f13d9695728188a28](https://github.com/user-attachments/assets/25c5768c-fa2a-4f22-8250-df03c3edd188)
![7cf6522893612549cd1710e59f05a8a6](https://github.com/user-attachments/assets/e9b20fb1-9c88-45bd-bef4-db940740a0c9)

**Comment by smthemex** [comment]
如果有diffuser的模型,安装我的说明里下载对应的,并在diffuser目录下建好文件夹,就可以不使用repo,因为是优先使用repo的,所以最后一张图,填写的那个D:\xxx 的时候，会优先使用这个地址，但是你的地址又是错的，因为是要填写D:/ComdyUI这种格式。  而你上面那张图倒是对的，不过报错让人很疑惑，很大的出错原因是你的秋叶整合包的diffuser版本低了（或者说不匹配）

**Comment by T8star1984** [comment]
我把之前的stable-diffusion-v1-5整个文件夹都删了，然后重新下了HF的文件，然后就正常了，谢谢您
