### ISSUE TITLE
I don't understand what this is about

### ISSUE THREAD

**Issue by wibur0620** [smthemex/ComfyUI_Stable_Makeup#8]
[ConfyUI.txt](https://github.com/user-attachments/files/16199076/ConfyUI.txt)
![image](https://github.com/user-attachments/assets/5ff8b319-646e-4c46-94ad-93568bf319b9)

**Comment by wibur0620** [comment]
![image](https://github.com/user-attachments/assets/b7d7b6f8-0abc-4816-b816-924b80d7899a)
When I change the parameter in the highlighted area of the image, it runs normally again.

**Comment by wibur0620** [comment]
The effect is very good, but I don't know why I can't use MobileNet in FaceDetector.
![image](https://github.com/user-attachments/assets/fe76b70d-9231-48bb-a391-32e36ac5386f)

**Comment by smthemex** [comment]
2个选项对应不同的模型，你检查一下第一个MobileNet模型是否名称正确。MobileNet的模型需要更名为我的说明文件里mobilenet0.25_Final.pth

**Comment by wibur0620** [comment]
> 2个选项对应不同的模型，你检查一下第一个MobileNet模型是否名称正确。MobileNet的模型需要更名为我的说明文件里mobilenet0.25_Final.pth
模型名称没问题。还是不能使用
![image](https://github.com/user-attachments/assets/cb132afa-6d62-4e92-b271-6e672d94804f)

**Comment by smthemex** [comment]
我迟点看看代码吧，好像我这本地测试是没问题的

**Comment by smthemex** [comment]
最近的更新，已经修复该问题。
